from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='diary/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('entry/', views.entry_create, name='entry-create'),
    path('entry/<int:pk>/', views.entry_detail, name='entry-detail'),
    path('entry/<int:pk>/edit/', views.entry_edit, name='entry-edit'),
    path('entry/autosave/', views.entry_autosave, name='entry-autosave'),
    path('tags/create/', views.tag_create, name='tag-create'),
    path('tags/<int:tag_id>/delete/', views.tag_delete, name='tag-delete'),
    path('tag/<int:tag_id>/delete/', views.tag_delete, name='tag-delete'),
    path('toggle-dark-mode/', views.toggle_dark_mode, name='toggle_dark_mode'),
    path('update-mood/', views.update_mood, name='update-mood'),
    path('entries/', views.entries_list, name='entries-list'),
    path('entry/<int:pk>/trash/', views.entry_trash, name='entry-trash'),
    path('entry/<int:pk>/restore/', views.entry_restore, name='entry-restore'),
    path('entry/<int:pk>/archive/', views.entry_archive, name='entry-archive'),
    path('entry/<int:pk>/unarchive/', views.entry_unarchive, name='entry-unarchive'),
    path('entry/<int:pk>/delete-permanent/', views.entry_permanent_delete, name='entry-permanent-delete'),
    path('entries/trash/', views.entries_trash, name='entries-trash'),
    path('entries/archive/', views.entries_archive, name='entries-archive'),
    path('goals/', views.goals_list, name='goals'),
    path('goals/create/', views.goal_create, name='goal-create'),
    path('goals/<int:pk>/toggle/', views.toggle_goal_completed, name='toggle-goal'),
    path('goals/<int:pk>/delete/', views.delete_goal, name='delete-goal'),
    path('goals/<int:goal_id>/subtask/add/', views.add_subtask, name='add-subtask'),
    path('goals/<int:goal_id>/subtask/<int:index>/toggle/', views.toggle_subtask, name='toggle-subtask'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('wishlist/<int:pk>/toggle/', views.toggle_wishlist_purchased, name='toggle-wishlist-item'),
    path('wishlist/<int:pk>/delete/', views.delete_wishlist_item, name='delete-wishlist-item'),
    path('goals/quick-add/', views.quick_add_goal, name='quick-add-goal'),
    path('wishlist/quick-add/', views.quick_add_wishlist, name='quick-add-wishlist'),
    path('settings/', views.profile_settings, name='profile-settings'),
    path('export-entries/', views.export_entries, name='export-entries'),
    path('analytics/', views.analytics_view, name='analytics'),
    path('entries/bulk-archive/', views.bulk_operation, {'operation': 'archive'}, name='bulk-archive'),
    path('entries/bulk-unarchive/', views.bulk_operation, {'operation': 'unarchive'}, name='bulk-unarchive'),
    path('entries/bulk-restore/', views.bulk_operation, {'operation': 'restore'}, name='bulk-restore'),
    path('entries/bulk-delete/', views.bulk_operation, {'operation': 'delete'}, name='bulk-delete'),
    path('entries/bulk-trash/', views.bulk_operation, {'operation': 'trash'}, name='bulk-trash'),
    path('goals/reorder/', views.reorder_goals, name='reorder-goals'),
    path('wishlist/reorder/', views.reorder_wishlist, name='reorder-wishlist'),
    path('api/moods/<int:year>/', views.get_year_moods, name='get-year-moods'),
    path('goals/<int:pk>/edit/', views.goal_edit, name='edit-goal'),
    path('wishlist/<int:pk>/edit/', views.wishlist_edit, name='edit-wishlist-item'),
]