# Generated by Django 5.1.7 on 2025-04-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_diaryentry_tags_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='tags',
            field=models.ManyToManyField(blank=True, to='diary.tag'),
        ),
    ]
