# Generated by Django 5.1.7 on 2025-04-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_diaryentry_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='emoji_of_day',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
