# Generated by Django 5.1.7 on 2025-04-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_dailymood_diaryentry_daily_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='is_autosave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('trash', 'Trash')], default='active', max_length=10),
        ),
    ]
