# Generated by Django 5.1.7 on 2025-04-27 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_diaryentry_deleted_at_diaryentry_is_autosave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='daily_mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='diary.dailymood'),
        ),
    ]
