# Generated by Django 5.1.7 on 2025-04-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_alter_diaryentry_daily_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='priority',
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
