# Generated by Django 5.1.7 on 2025-05-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_alter_goal_options_alter_goal_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['completed', models.OrderBy(models.F('deadline'), nulls_last=True), '-created_at']},
        ),
    ]
