# Generated by Django 5.1.7 on 2025-05-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_alter_goal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['completed', models.OrderBy(models.F('deadline'), nulls_first=True), '-created_at']},
        ),
    ]
