# Generated by Django 5.1.7 on 2025-05-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_alter_goal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='priority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
