# Generated by Django 5.1.7 on 2025-05-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_wishlistitem_created_at_alter_wishlistitem_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['purchased', models.OrderBy(models.F('priority'), descending=True, nulls_first=True), '-created_at']},
        ),
    ]
