# Generated by Django 5.1.7 on 2025-05-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0015_alter_wishlistitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['purchased', models.OrderBy(models.F('priority'), nulls_first=True), '-created_at']},
        ),
    ]
