# Generated by Django 5.1.7 on 2025-05-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_alter_wishlistitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enable_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
